#! /usr/bin/env python

import os
from glob import glob
from pathlib import Path

env = SConscript("../../godot-cpp/SConstruct")

env.Append(CPPPATH=["src/"])
#env.Append(CCFLAGS=["-DCHESS_NO_EXCEPTIONS"])
sources = glob("*cpp")
sources.extend(glob("src/*cpp"))
#sources += glob(" src/*cpp")
print(sources)

extension_path = "./libalephone.gdextension"
addon_path = Path(extension_path).parent

project_name = Path(extension_path).stem

scons_cache_path = os.environ.get("SCONS_CACHE")

if scons_cache_path is not None:
    CacheDir(scons_cache_path)
    print("Scons cache enabled... (path: '" + scons_cache_path + "')")

debug_or_release = "debug"

library = env.SharedLibrary(
        "{}/bin/{}.{}.{}.{}{}".format(
            addon_path,
            project_name,
            env["platform"],
            debug_or_release,
            env["arch"],
            env["SHLIBSUFFIX"],
        ),
        source=sources
)

Default(library)
